API_KEY = "6e2d2b3f-636a-424a-a97e-5154e39e525a"
SECRET_KEY = "D4B9966385BEE5A7B7D8791BA5C0539F"
PASSPHRASE = "Ta123456&"

TELEGRAM_TOKEN = "8300868885:AAEx8Zxdkz9CRUHmjJ0vvn6L3kC2kOPCHuk"
TELEGRAM_CHAT_ID = "658712542"

SYMBOLS = [
    "CRV-USDT", "GALA-USDT", "BNB-USDT", "SOL-USDT", "ADA-USDT", "AVAX-USDT",
    "ATOM-USDT", "DOT-USDT", "TRUMP-USDT", "LINK-USDT", "UNI-USDT", "AAVE-USDT",
    "SUSHI-USDT", "LDO-USDT", "INJ-USDT", "XRP-USDT", "FET-USDT", "APE-USDT",
    "TIA-USDT", "OP-USDT", "MANA-USDT", "THETA-USDT", "CHZ-USDT", "ENJ-USDT",
    "AXS-USDT", "GRT-USDT", "MKR-USDT", "COMP-USDT", "ZRX-USDT", "SNX-USDT",
    "ALGO-USDT", "PEPE-USDT", "NEAR-USDT", "CRO-USDT", "KSM-USDT", "ONE-USDT",
    "SAND-USDT", "CFX-USDT", "BAT-USDT", "ILV-USDT", "XLM-USDT",
]

TIMEFRAME = "5m"
TRADE_AMOUNT_USDT = 25
STOP_LOSS_PCT = 0.02
TAKE_PROFIT_PCT = 0.06
MAX_OPEN_POSITIONS = 4
